# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cipher', models.CharField(max_length=15)),
                ('revision', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ('cipher', 'revision'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='pcb',
            unique_together=set([('cipher', 'revision')]),
        ),
    ]
