# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOMs',
                'ordering': ('pcb',),
            },
        ),
        migrations.AlterModelOptions(
            name='pcb',
            options={'ordering': ('cipher', 'revision'), 'verbose_name': 'PCB', 'verbose_name_plural': 'PCBs'},
        ),
        migrations.AddField(
            model_name='bom',
            name='pcb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb.Pcb'),
        ),
    ]
