# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0003_auto_20170416_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pcb.Component')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            bases=('pcb.component',),
        ),
        migrations.RenameField(
            model_name='resistor',
            old_name='resistance',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='bom',
            name='components',
            field=models.ManyToManyField(through='pcb.BomComponent', to='pcb.Component', verbose_name='components'),
        ),
    ]
