# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0006_auto_20170416_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='pcb',
        ),
        migrations.AddField(
            model_name='pcb',
            name='bom',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pcb', to='pcb.Bom'),
            preserve_default=False,
        ),
    ]
