# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0008_auto_20170416_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='description',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
