# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0009_bom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(null=True, upload_to='components_images'),
        ),
    ]
