# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0011_auto_20170420_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=5)),
                ('sch', models.FileField(upload_to='schematic')),
            ],
        ),
        migrations.AddField(
            model_name='pcb',
            name='pcb',
            field=models.FileField(default='', upload_to='pcb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schematic',
            name='pcb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb.Pcb'),
        ),
    ]
