# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import pcb.models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0013_pcb_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcb',
            name='order_files',
            field=models.FileField(default='', upload_to='order_files', validators=[pcb.models.file_zip]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcb',
            name='order_list',
            field=models.FileField(default='', upload_to='order_list', validators=[pcb.models.file_doc]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcb',
            name='pcb',
            field=models.FileField(upload_to='pcb', validators=[pcb.models.file_pdf]),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='sch',
            field=models.FileField(upload_to='schematic', validators=[pcb.models.file_pdf]),
        ),
    ]
