# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0014_auto_20170420_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcb',
            old_name='order_files',
            new_name='orderfiles',
        ),
        migrations.RenameField(
            model_name='pcb',
            old_name='order_list',
            new_name='orderlist',
        ),
    ]
