# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0015_auto_20170420_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ('pcb',), 'verbose_name': 'Перечень элементов', 'verbose_name_plural': 'Перечни элементов'},
        ),
        migrations.AlterModelOptions(
            name='bomcomponent',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterModelOptions(
            name='pcb',
            options={'ordering': ('cipher', 'revision'), 'verbose_name': 'Печатная плата', 'verbose_name_plural': 'Печатные платы'},
        ),
        migrations.AlterModelOptions(
            name='schematic',
            options={'verbose_name': 'Схема принципиальная электрическая', 'verbose_name_plural': 'Схемы принципиальные электрические'},
        ),
        migrations.AlterField(
            model_name='bom',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Рабочая'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='components',
            field=models.ManyToManyField(related_name='bom', through='pcb.BomComponent', to='components.Component', verbose_name='Компоненты'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='description',
            field=models.CharField(max_length=60, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='pcb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='pcb.Pcb', verbose_name='Печатная плата'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='annotation',
            field=models.CharField(max_length=10, verbose_name='Позиционное обозначение'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomcomponent', to='pcb.Bom', verbose_name='Перечень элементов'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomcomponent', to='components.Component', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='cipher',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Наименовение'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='orderfiles',
            field=models.FileField(upload_to='order_files', verbose_name='Архив для заказа'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='orderlist',
            field=models.FileField(upload_to='order_list', verbose_name='Лист заказ'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='pcb',
            field=models.FileField(upload_to='pcb', verbose_name='Топология'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='project',
            field=models.CharField(max_length=300, verbose_name='Ссылка на проект'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='revision',
            field=models.CharField(max_length=1, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='pcb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematic', to='pcb.Pcb', verbose_name='Печатная плата'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='sch',
            field=models.FileField(upload_to='schematic', verbose_name='Файл схемы'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='sheet',
            field=models.CharField(max_length=5, verbose_name='Лист'),
        ),
        migrations.AlterIndexTogether(
            name='pcb',
            index_together=set([('cipher', 'revision')]),
        ),
    ]
