# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0017_auto_20170424_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcb',
            name='pcb',
            field=models.FileField(upload_to='pcb', verbose_name='Монтажный чертеж'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='sheet',
            field=models.CharField(max_length=20, verbose_name='Лист'),
        ),
    ]
