# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components_images')),
            ],
        ),
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='Resistor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='Transistor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('type', models.CharField(max_length=20)),
            ],
            bases=('components.component',),
        ),
        migrations.AddField(
            model_name='component',
            name='footprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Footprint'),
        ),
    ]
