# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitor',
            options={'ordering': ['footprint', 'value']},
        ),
        migrations.AlterModelOptions(
            name='resistor',
            options={'ordering': ['footprint', 'value']},
        ),
        migrations.AlterModelOptions(
            name='transistor',
            options={'ordering': ['type', 'footprint']},
        ),
        migrations.AddField(
            model_name='component',
            name='class_name',
            field=models.CharField(default='', editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(default='', upload_to='components_images'),
            preserve_default=False,
        ),
    ]
