# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20170421_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='class_name',
            field=models.CharField(max_length=30),
        ),
    ]
