# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20170421_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='class_name',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
