# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20170421_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='class_name',
            new_name='detail_name',
        ),
    ]
