# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20170421_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='comment',
            field=models.CharField(default='not provided', editable=False, max_length=80),
            preserve_default=False,
        ),
    ]
