# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_component_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitor',
            name='voltage',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
