# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_capacitor_voltage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitor',
            options={'ordering': ['footprint', 'value'], 'verbose_name': 'Конденсатор', 'verbose_name_plural': 'Конденсаторы'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterModelOptions(
            name='footprint',
            options={'verbose_name': 'Посадочное место', 'verbose_name_plural': 'Посадочные места'},
        ),
        migrations.AlterModelOptions(
            name='resistor',
            options={'ordering': ['footprint', 'value'], 'verbose_name': 'Резистор', 'verbose_name_plural': 'Резисторы'},
        ),
        migrations.AlterModelOptions(
            name='transistor',
            options={'ordering': ['type', 'footprint'], 'verbose_name': 'Транзистор', 'verbose_name_plural': 'Транзисторы'},
        ),
        migrations.AlterField(
            model_name='capacitor',
            name='value',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='capacitor',
            name='voltage',
            field=models.PositiveIntegerField(db_index=True, default=5, verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='component',
            name='footprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Footprint', verbose_name='Посадочное место'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(upload_to='components_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Партномер'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='resistor',
            name='value',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='type',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterIndexTogether(
            name='capacitor',
            index_together=set([('value', 'voltage')]),
        ),
    ]
