# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20170424_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitor',
            name='value',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Номинал'),
        ),
    ]
